#!/bin/sh
if test "$#" -ne "2"
then
	echo "Incorrect number of arguments " >&2
	echo "Please try with: <CSV_file> <base_UID>" >&2
fi
i="1"
UID=$2
var=$(cat $1)
echo "$var" | ( while read line
do
	if test "$i" -eq "1"
	then
	i=$((i+1))
	continue
	else
	login=$(echo $line | cut -d ";"  -f 1 ) > /dev/null
	personalFolder="/home/$login" 
	UID=$(expr $UID + 1)
	comment=$(echo $line | cut -d ";" -f 2-3 | tr -s ";" ",") > /dev/null
	interpreter="/bin/bash"
	GID=$(echo $line | cut -d ";" -f 4) > /dev/null
	echo "$login:x:$UID:$GID:$comment:$personalFolder:$interpreter" >> ./my_passwd3
	fi
done
exit 0)
