#!/bin/sh


if test "$#" -ne "1"
then
        echo "The number of arguments is not correct" >&2 #>&2 print the error to the standar error 
        echo "USE: $0 <base_UID>" >&2
        exit 1
fi
var=$(getent passwd |cut -d ":" -f 3 | sort -n)
lastUID=$(getent passwd |cut -d ":" -f 3 | sort -n | tail -n 1)
cont=$1
echo "$var" | ( while read line
do
	if test "$cont" -gt "$lastUID"
	then
		echo "$cont"
		exit 0
	elif test $(echo "$var" | grep -v "$cont" > /dev/null)
	then
		echo "$cont"
        	exit 0
	elif test "$line" -gt "$cont"
	then
		echo "$cont"
		exit 0
	elif test "$line" -lt "$cont"
	then
		continue
	
	else
		cont=$(($cont + 1))
	fi	

done )

exit 0
